site_name: The Sandbox Game
site_url: https://the-sandbox-game.readthedocs.io
theme:
  name: material
  features:
    - navigation.indexes
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
#nav: WE USE https://github.com/oprypin/mkdocs-literate-nav plugin add navigation in SUMMARY.MD !!!
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: '#'
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
